name: formdakal
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Mevcut Paketler
  shared_preferences: ^2.2.3
  provider: ^6.1.2
  image_picker: ^1.1.2
  cupertino_icons: ^1.0.2
  uuid: ^4.4.0
  intl: ^0.19.0
  collection: ^1.18.0
  fl_chart: ^0.68.0
  share_plus: ^9.0.0
  path_provider: ^2.1.3
  flutter_local_notifications: ^17.2.1
  sensors_plus: ^5.0.1
  permission_handler: ^11.3.1
  timezone: ^0.9.2
  
  # YENİ EKLENEN - Adım sayacı
  pedometer: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# Flutter'ın genel ayarları
flutter:
  uses-material-design: true
  assets:
    - assets/images/